### ISSUE TITLE
Counter initialization in Integrator

### ISSUE THREAD

**Issue by chengyh23** [callum-rhodes/gabp_mapping#3]
https://github.com/callum-rhodes/gabp_mapping/blob/a8d0f121b048f400454037bb3f93361c0ef61d56/scripts/throttlePID.py#L38-L53

Should initialization be `i=0` rather than `i=1`?

**Comment by callum-rhodes** [comment]
Hi, Since we are counting from the end of the array backwards we need to start indexing at [-1]. If you start from [-0] you would be taking the first element of the array and then in the next iteration taking the last element at [-1]. Hope that clears that up.
