### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by chengyh23** [callum-rhodes/gabp_mapping#4]
https://github.com/callum-rhodes/gabp_mapping/blob/a8d0f121b048f400454037bb3f93361c0ef61d56/scripts/throttlePID.py#L11-L12

rospy loginfo is mistaken

**Comment by callum-rhodes** [comment]
Yep I doubled up the loginfo so this one should not be there. Since it's not a major issue maybe you can add it to the fix for indentation issue you were seeing and then submit a pull request for both.
